apiVersion: v1
kind: Service
metadata:
  name: {{ template "creator.fullname" . }}
  labels:
    app: {{ template "creator.fullname" . }}
    app.kubernetes.io/name: origin
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: origin-creator
spec:
  type: NodePort
  selector:
    app: {{ template "creator.fullname" . }}
  ports:
  - name: nginx
    port: 80
  - name: api
    port: 4321

