apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "creator-issuer.fullname" . }}
  labels:
    app: {{ template "creator-issuer.fullname" . }}
    app.kubernetes.io/name: origin
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: origin-creator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "creator-issuer.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "creator-issuer.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: creator-issuer
        image: "{{ .Values.containerRegistry }}/{{ .Release.Namespace }}/{{ .Values.creatorIssuerImage }}:{{ .Values.creatorIssuerImageTag }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: SERVER_ENDPOINT
            value: {{ template "dapp.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        volumeMounts:
          - name: {{ template "creator-issuer.fullname" . }}-data
            mountPath: /etc/resty-auto-ssl
  volumeClaimTemplates:
  - metadata:
      name: {{ template "creator-issuer.fullname" . }}-data
    spec:
      storageClassName: "standard"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
