{{- if eq .Release.Namespace "staging" }}
# Permanent redirect for demo.originprotocol.com
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-originprotocol-redirect
  labels:
    app: {{ template "dapp.fullname" . }}
    app.kubernetes.io/name: origin
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: origin-dapp
  annotations:
    kubernetes.io/ingress.class: {{ .Release.Namespace }}-ingress
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.clusterIssuer }}
    # Disable SSL redirect to prevent double redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://dapp.originprotocol.com"
spec:
  tls:
    - secretName: demo.originprotocol.com
      hosts:
        - demo.originprotocol.com
  rules:
  - host: demo.originprotocol.com
    http:
      paths:
      - backend:
          serviceName: {{ template "dapp.fullname" . }}
          servicePort: 80
{{- end }}
