apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "discovery.fullname" . }}
  labels:
    app: {{ template "discovery.fullname" . }}
    app.kubernetes.io/name: origin
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: origin-discovery
spec:
  replicas: {{ default 2 .Values.discoveryReplicas }}
  selector:
    matchLabels:
      app: {{ template "discovery.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "discovery.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '4000'
    spec:
      containers:
      - name: origin-discovery
        image: "{{ .Values.containerRegistry }}/{{ .Release.Namespace }}/{{ .Values.discoveryImage }}:{{ .Values.discoveryImageTag }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 4000
        env:
        - name: ENVKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "discovery.fullname" . }}
              key: ENVKEY
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances={{ .Values.databaseInstance }}=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
