apiVersion: v1
kind: Secret
metadata:
  name: {{ template "faucet.fullname" . }}
  labels:
    app: {{ template "faucet.fullname" . }}
    app.kubernetes.io/name: origin
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: origin-faucet
type: Opaque
data:
  ENVKEY: {{ required "Set a .Values.faucetEnvKey" .Values.faucetEnvKey | b64enc | quote}}
