apiVersion: v1
kind: Service
metadata:
  name: {{ template "messaging.fullname" . }}
  labels:
    app: {{ template "messaging.fullname" . }}
    app.kubernetes.io/name: origin
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: origin-messaging
spec:
  type: NodePort
  selector:
    app: {{ template "messaging.fullname" . }}
  ports:
  - name: https
    port: 443
  - name: ipfs-api
    port: 5001
  - name: websocket
    port: 9012
  - name: api
    port: 6647
