apiVersion: v1
kind: Secret
metadata:
  name: {{ template "messaging.fullname" . }}
  labels:
    app: {{ template "messaging.fullname" . }}
    app.kubernetes.io/name: origin
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: origin-messaging
type: Opaque
data:
  ENVKEY: {{ required "Set a .Values.messagingEnvKey" .Values.messagingEnvKey | b64enc | quote}}
