apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@originprotocol.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
    dns01:
      providers:
        - name: google-cloud-dns
          clouddns:
            # A secretKeyRef to a google cloud json service account
            serviceAccountSecretRef:
              name: gcloud-creator-sa-credentials
              key: credentials.json
            project: origin-214503
