databaseInstance: origin-214503:us-west1:dev

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: '09d63fe'

# origin-dapp
dappImage: origin-dapp
dappImageTag: '9d84946'

# origin-ipfs-proxy
ipfsProxyImage: origin-ipfs-proxy
ipfsProxyImageTag: 'ed37ae1'

# origin-faucet
faucetImage: origin-faucet
faucetImageTag: '8c30f02'

# event-listener
eventlistenerImage: event-listener
eventlistenerImageTag: '09b62a6'

# origin-discovery
discoveryImage: origin-discovery
discoveryImageTag: '612853d'

# origin-growth
growthImage: origin-growth
growthImageTag: '07155ef'

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: 'b739587'

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: '1f7d565'

# origin-dapp-creator-client
creatorClientImage: origin-dapp-creator-client
creatorClientImageTag: '0e70329'

# origin-dapp-creator-server
creatorServerImage: origin-dapp-creator-server
creatorServerImageTag: '8c30f02'

# origin-dapp-creator-issuer
creatorIssuerImage: origin-dapp-creator-issuer
creatorIssuerImageTag: 'latest'
creatorIssuerIp: '35.233.181.44'

# origin-cron
cronImage: origin-cron
cronImageTag: '9898f9d'

# origin-admin
adminImage: origin-admin
adminImageTag: '09d63fe'
