controller:
  service:
    loadBalancerIP: 35.197.88.39
    externalTrafficPolicy: "Local"
  ingressClass: staging-ingress
  stats:
    enabled: true
  metrics:
    enabled: true
  extraArgs:
    enable-ssl-chain-completion: false
    watch-namespace: staging
    force-namespace-isolation: true
