version: "3"

services:
  origin-tests:
    container_name: origin-tests
    image: origin
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://origin:origin@postgres/origin
    volumes:
      - ./packagges/contracts/build:/app/packages/contracts/build
      - ./infra/tests/test:/app/infra/tests/test
    command:
      >
      /bin/bash -c "wait-for.sh -t 0 -q event-listener:9499 --
      sleep 10 &&
      npm run test --prefix origin-tests"

