name: ethereum-nodes
description: Deploy reliable and scalable Ethereum nodes
version: 0.1.0
home: https://github.com/OriginProtocol
icon: https://www.ethereum.org/images/logos/ETHEREUM-ICON_Black_small.png
sources:
  - https://github.com/OriginProtocol/origin/devops/kubernetes/charts/ethereum-nodes

